using System.ComponentModel;

namespace RustRcon
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            menuStrip = new MenuStrip();
            serverToolStripMenuItem = new ToolStripMenuItem();
            connectToolStripMenuItem = new ToolStripMenuItem();
            disconnectToolStripMenuItem = new ToolStripMenuItem();
            toolStripSeparator1 = new ToolStripSeparator();
            exitToolStripMenuItem = new ToolStripMenuItem();
            styleToolStripMenuItem = new ToolStripMenuItem();
            aboutToolStripMenuItem = new ToolStripMenuItem();
            tabControl = new TabControl();
            tabPageConsole = new TabPage();
            richTextBoxLogs = new RichTextBox();
            panelConsoleControls = new Panel();
            textBoxChatMessage = new TextBox();
            textBoxCommand = new TextBox();
            buttonSendCommand = new Button();
            panelLeft = new Panel();
            groupBoxPlayers = new GroupBox();
            flowLayoutPanelPlayers = new FlowLayoutPanel();
            labelOnlineCount = new Label();
            textBoxPlayerSearch = new TextBox();
            listViewBans = new ListView();
            columnHeaderBanName = new ColumnHeader();
            columnHeaderBanSteamID = new ColumnHeader();
            columnHeaderBanReason = new ColumnHeader();
            columnHeaderBanDate = new ColumnHeader();
            panelStatisticsMain = new Panel();
            listViewPlayerStats = new ListView();
            columnHeaderStatsSteamID = new ColumnHeader();
            columnHeaderNickname = new ColumnHeader();
            columnHeaderPVPKills = new ColumnHeader();
            columnHeaderPVPDeaths = new ColumnHeader();
            columnHeaderPVEDeaths = new ColumnHeader();
            panelStatsControls = new Panel();
            labelPlayerCount = new Label();
            textBoxFilterStats = new TextBox();
            labelFilterStats = new Label();
            listViewPlayerKills = new ListView();
            columnHeaderKillDate = new ColumnHeader();
            columnHeaderKillType = new ColumnHeader();
            columnHeaderKillTarget = new ColumnHeader();
            labelPlayerKills = new Label();
            panelStatisticsRight = new Panel();
            groupBoxOnlinePlayers = new GroupBox();
            textBoxSearchLogs = new TextBox();
            labelSearchLogs = new Label();
            tabPagePlayers = new TabPage();
            listViewPlayers = new ListView();
            columnHeaderName = new ColumnHeader();
            columnHeaderSteamID = new ColumnHeader();
            columnHeaderIP = new ColumnHeader();
            columnHeaderConnected = new ColumnHeader();
            panelRight = new Panel();
            groupBoxScheduledCommands = new GroupBox();
            listBoxScheduledCommands = new ListBox();
            buttonNewScheduledCommand = new Button();
            groupBoxTriggeredCommands = new GroupBox();
            listBoxTriggeredCommands = new ListBox();
            buttonNewTriggeredCommand = new Button();
            groupBoxHighlightSystem = new GroupBox();
            listBoxHighlights = new ListBox();
            buttonAddHighlight = new Button();
            groupBoxConsoleFilters = new GroupBox();
            listBoxFilters = new ListBox();
            buttonNewFilter = new Button();
            panelBottom = new Panel();
            statusStrip = new StatusStrip();
            toolStripStatusLabel = new ToolStripStatusLabel();
            toolStripStatusLabelConnected = new ToolStripStatusLabel();
            toolStripStatusLabelPlayers = new ToolStripStatusLabel();
            menuStrip.SuspendLayout();
            tabControl.SuspendLayout();
            tabPageConsole.SuspendLayout();
            panelConsoleControls.SuspendLayout();
            panelLeft.SuspendLayout();
            panelStatisticsMain.SuspendLayout();
            panelStatsControls.SuspendLayout();
            panelStatisticsRight.SuspendLayout();
            groupBoxOnlinePlayers.SuspendLayout();
            tabPagePlayers.SuspendLayout();
            panelRight.SuspendLayout();
            groupBoxScheduledCommands.SuspendLayout();
            groupBoxTriggeredCommands.SuspendLayout();
            groupBoxHighlightSystem.SuspendLayout();
            groupBoxConsoleFilters.SuspendLayout();
            statusStrip.SuspendLayout();
            SuspendLayout();
            menuStrip.Items.AddRange(new ToolStripItem[] { serverToolStripMenuItem, styleToolStripMenuItem });
            menuStrip.Location = new Point(0, 0);
            menuStrip.Name = "menuStrip";
            menuStrip.Size = new Size(1200, 24);
            menuStrip.TabIndex = 0;
            menuStrip.Text = "menuStrip1";
            serverToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { connectToolStripMenuItem, disconnectToolStripMenuItem, toolStripSeparator1, exitToolStripMenuItem });
            serverToolStripMenuItem.Name = "serverToolStripMenuItem";
            serverToolStripMenuItem.Size = new Size(51, 20);
            serverToolStripMenuItem.Text = "Server";
            connectToolStripMenuItem.Name = "connectToolStripMenuItem";
            connectToolStripMenuItem.Size = new Size(133, 22);
            connectToolStripMenuItem.Text = "Connect";
            connectToolStripMenuItem.Click += connectToolStripMenuItem_Click;
            disconnectToolStripMenuItem.Enabled = false;
            disconnectToolStripMenuItem.Name = "disconnectToolStripMenuItem";
            disconnectToolStripMenuItem.Size = new Size(133, 22);
            disconnectToolStripMenuItem.Text = "Disconnect";
            disconnectToolStripMenuItem.Click += disconnectToolStripMenuItem_Click;
            toolStripSeparator1.Name = "toolStripSeparator1";
            toolStripSeparator1.Size = new Size(130, 6);
            exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            exitToolStripMenuItem.Size = new Size(133, 22);
            exitToolStripMenuItem.Text = "Exit";
            exitToolStripMenuItem.Click += exitToolStripMenuItem_Click;
            styleToolStripMenuItem.Name = "styleToolStripMenuItem";
            styleToolStripMenuItem.Size = new Size(44, 20);
            styleToolStripMenuItem.Text = "Style";
            aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            aboutToolStripMenuItem.Size = new Size(107, 22);
            aboutToolStripMenuItem.Text = "About";
            aboutToolStripMenuItem.Click += aboutToolStripMenuItem_Click;
            tabControl.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tabControl.Controls.Add(tabPageConsole);
            tabControl.Location = new Point(0, 24);
            tabControl.Name = "tabControl";
            tabControl.SelectedIndex = 0;
            tabControl.Size = new Size(1200, 400);
            tabControl.TabIndex = 1;
            tabPageConsole.Controls.Add(richTextBoxLogs);
            tabPageConsole.Controls.Add(panelConsoleControls);
            tabPageConsole.Controls.Add(panelLeft);
            tabPageConsole.Location = new Point(4, 24);
            tabPageConsole.Name = "tabPageConsole";
            tabPageConsole.Padding = new Padding(3);
            tabPageConsole.Size = new Size(1192, 372);
            tabPageConsole.TabIndex = 0;
            tabPageConsole.Text = "Console";
            tabPageConsole.UseVisualStyleBackColor = true;
            richTextBoxLogs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            richTextBoxLogs.BackColor = Color.FromArgb(30, 30, 30);
            richTextBoxLogs.Font = new Font("Consolas", 9F);
            richTextBoxLogs.ForeColor = Color.Yellow;
            richTextBoxLogs.Location = new Point(212, 6);
            richTextBoxLogs.Name = "richTextBoxLogs";
            richTextBoxLogs.ReadOnly = true;
            richTextBoxLogs.Size = new Size(974, 290);
            richTextBoxLogs.TabIndex = 0;
            richTextBoxLogs.Text = "";
            panelConsoleControls.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            panelConsoleControls.Controls.Add(textBoxChatMessage);
            panelConsoleControls.Controls.Add(textBoxCommand);
            panelConsoleControls.Controls.Add(buttonSendCommand);
            panelConsoleControls.Location = new Point(212, 302);
            panelConsoleControls.Name = "panelConsoleControls";
            panelConsoleControls.Size = new Size(974, 34);
            panelConsoleControls.TabIndex = 1;
            textBoxChatMessage.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            textBoxChatMessage.Location = new Point(5, 5);
            textBoxChatMessage.Name = "textBoxChatMessage";
            textBoxChatMessage.PlaceholderText = "Type a chat message";
            textBoxChatMessage.Size = new Size(300, 23);
            textBoxChatMessage.TabIndex = 0;
            textBoxChatMessage.KeyPress += textBoxChatMessage_KeyPress;
            textBoxCommand.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            textBoxCommand.Location = new Point(315, 5);
            textBoxCommand.Name = "textBoxCommand";
            textBoxCommand.PlaceholderText = "Type a command to execute";
            textBoxCommand.Size = new Size(300, 23);
            textBoxCommand.TabIndex = 1;
            textBoxCommand.KeyPress += textBoxCommand_KeyPress;
            buttonSendCommand.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            buttonSendCommand.Enabled = false;
            buttonSendCommand.Location = new Point(625, 5);
            buttonSendCommand.Name = "buttonSendCommand";
            buttonSendCommand.Size = new Size(75, 23);
            buttonSendCommand.TabIndex = 2;
            buttonSendCommand.Text = "Send";
            buttonSendCommand.UseVisualStyleBackColor = true;
            buttonSendCommand.Click += buttonSendCommand_Click;
            panelLeft.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
            panelLeft.Controls.Add(groupBoxPlayers);
            panelLeft.Location = new Point(6, 6);
            panelLeft.Name = "panelLeft";
            panelLeft.Size = new Size(200, 330);
            panelLeft.TabIndex = 0;
            groupBoxPlayers.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxPlayers.Controls.Add(flowLayoutPanelPlayers);
            groupBoxPlayers.Controls.Add(labelOnlineCount);
            groupBoxPlayers.Controls.Add(textBoxPlayerSearch);
            groupBoxPlayers.Location = new Point(0, 0);
            groupBoxPlayers.Name = "groupBoxPlayers";
            groupBoxPlayers.Size = new Size(200, 330);
            groupBoxPlayers.TabIndex = 0;
            groupBoxPlayers.TabStop = false;
            groupBoxPlayers.Text = "";
            flowLayoutPanelPlayers.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            flowLayoutPanelPlayers.AutoScroll = true;
            flowLayoutPanelPlayers.FlowDirection = FlowDirection.TopDown;
            flowLayoutPanelPlayers.WrapContents = false;
            flowLayoutPanelPlayers.Location = new Point(6, 50);
            flowLayoutPanelPlayers.Name = "flowLayoutPanelPlayers";
            flowLayoutPanelPlayers.Size = new Size(188, 250);
            flowLayoutPanelPlayers.TabIndex = 1;
            labelOnlineCount.AutoSize = true;
            labelOnlineCount.Location = new Point(6, 5);
            labelOnlineCount.Name = "labelOnlineCount";
            labelOnlineCount.Size = new Size(100, 15);
            labelOnlineCount.TabIndex = 0;
            labelOnlineCount.Text = "Online Players: 0";
            textBoxPlayerSearch.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            textBoxPlayerSearch.Location = new Point(6, 25);
            textBoxPlayerSearch.Name = "textBoxPlayerSearch";
            textBoxPlayerSearch.PlaceholderText = "Search players...";
            textBoxPlayerSearch.Size = new Size(188, 23);
            textBoxPlayerSearch.TabIndex = 2;
            textBoxPlayerSearch.TextChanged += textBoxPlayerSearch_TextChanged;
            listViewBans.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listViewBans.Columns.AddRange(new ColumnHeader[] { columnHeaderBanName, columnHeaderBanSteamID, columnHeaderBanReason, columnHeaderBanDate });
            listViewBans.FullRowSelect = true;
            listViewBans.GridLines = true;
            listViewBans.Location = new Point(6, 6);
            listViewBans.Name = "listViewBans";
            listViewBans.Size = new Size(780, 360);
            listViewBans.TabIndex = 0;
            listViewBans.UseCompatibleStateImageBehavior = false;
            listViewBans.View = View.Details;
            columnHeaderBanName.Text = "Name";
            columnHeaderBanName.Width = 200;
            columnHeaderBanSteamID.Text = "Steam ID";
            columnHeaderBanSteamID.Width = 150;
            columnHeaderBanReason.Text = "Reason";
            columnHeaderBanReason.Width = 200;
            columnHeaderBanDate.Text = "Date";
            columnHeaderBanDate.Width = 150;
            panelStatisticsMain.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            panelStatisticsMain.Controls.Add(listViewPlayerStats);
            panelStatisticsMain.Controls.Add(panelStatsControls);
            panelStatisticsMain.Controls.Add(listViewPlayerKills);
            panelStatisticsMain.Controls.Add(labelPlayerKills);
            panelStatisticsMain.Location = new Point(6, 6);
            panelStatisticsMain.Name = "panelStatisticsMain";
            panelStatisticsMain.Size = new Size(1180, 360);
            panelStatisticsMain.TabIndex = 0;
            listViewPlayerStats.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            listViewPlayerStats.Columns.AddRange(new ColumnHeader[] { columnHeaderStatsSteamID, columnHeaderNickname, columnHeaderPVPKills, columnHeaderPVPDeaths, columnHeaderPVEDeaths });
            listViewPlayerStats.FullRowSelect = true;
            listViewPlayerStats.GridLines = true;
            listViewPlayerStats.Location = new Point(0, 0);
            listViewPlayerStats.Name = "listViewPlayerStats";
            listViewPlayerStats.Size = new Size(1180, 200);
            listViewPlayerStats.TabIndex = 0;
            listViewPlayerStats.UseCompatibleStateImageBehavior = false;
            listViewPlayerStats.View = View.Details;
            listViewPlayerStats.SelectedIndexChanged += listViewPlayerStats_SelectedIndexChanged;
            columnHeaderStatsSteamID.Text = "SteamID";
            columnHeaderStatsSteamID.Width = 120;
            columnHeaderNickname.Text = "Nickname";
            columnHeaderNickname.Width = 150;
            columnHeaderPVPKills.Text = "PVP Kills";
            columnHeaderPVPKills.Width = 80;
            columnHeaderPVPDeaths.Text = "PVP Deaths";
            columnHeaderPVPDeaths.Width = 80;
            columnHeaderPVEDeaths.Text = "PVE Deaths";
            columnHeaderPVEDeaths.Width = 80;
            panelStatsControls.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            panelStatsControls.Controls.Add(labelPlayerCount);
            panelStatsControls.Controls.Add(textBoxFilterStats);
            panelStatsControls.Controls.Add(labelFilterStats);
            panelStatsControls.Location = new Point(0, 206);
            panelStatsControls.Name = "panelStatsControls";
            panelStatsControls.Size = new Size(1180, 30);
            panelStatsControls.TabIndex = 1;
            labelPlayerCount.AutoSize = true;
            labelPlayerCount.Location = new Point(90, 6);
            labelPlayerCount.Name = "labelPlayerCount";
            labelPlayerCount.Size = new Size(53, 15);
            labelPlayerCount.TabIndex = 1;
            labelPlayerCount.Text = "0 players";
            textBoxFilterStats.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            textBoxFilterStats.Location = new Point(450, 3);
            textBoxFilterStats.Name = "textBoxFilterStats";
            textBoxFilterStats.Size = new Size(100, 23);
            textBoxFilterStats.TabIndex = 2;
            textBoxFilterStats.TextChanged += textBoxFilterStats_TextChanged;
            labelFilterStats.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            labelFilterStats.AutoSize = true;
            labelFilterStats.Location = new Point(400, 6);
            labelFilterStats.Name = "labelFilterStats";
            labelFilterStats.Size = new Size(36, 15);
            labelFilterStats.TabIndex = 3;
            labelFilterStats.Text = "Filter:";
            listViewPlayerKills.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listViewPlayerKills.Columns.AddRange(new ColumnHeader[] { columnHeaderKillDate, columnHeaderKillType, columnHeaderKillTarget });
            listViewPlayerKills.FullRowSelect = true;
            listViewPlayerKills.GridLines = true;
            listViewPlayerKills.Location = new Point(0, 250);
            listViewPlayerKills.Name = "listViewPlayerKills";
            listViewPlayerKills.Size = new Size(1180, 110);
            listViewPlayerKills.TabIndex = 2;
            listViewPlayerKills.UseCompatibleStateImageBehavior = false;
            listViewPlayerKills.View = View.Details;
            columnHeaderKillDate.Text = "Date";
            columnHeaderKillDate.Width = 150;
            columnHeaderKillType.Text = "Event Type";
            columnHeaderKillType.Width = 100;
            columnHeaderKillTarget.Text = "Killer/Killed";
            columnHeaderKillTarget.Width = 300;
            labelPlayerKills.AutoSize = true;
            labelPlayerKills.Location = new Point(0, 232);
            labelPlayerKills.Name = "labelPlayerKills";
            labelPlayerKills.Size = new Size(129, 15);
            labelPlayerKills.TabIndex = 3;
            labelPlayerKills.Text = "Events for player: None";
            panelStatisticsRight.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right;
            panelStatisticsRight.Location = new Point(592, 6);
            panelStatisticsRight.Name = "panelStatisticsRight";
            panelStatisticsRight.Size = new Size(194, 360);
            panelStatisticsRight.TabIndex = 1;
            groupBoxOnlinePlayers.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            groupBoxOnlinePlayers.Location = new Point(0, 0);
            groupBoxOnlinePlayers.Name = "groupBoxOnlinePlayers";
            groupBoxOnlinePlayers.Size = new Size(194, 360);
            groupBoxOnlinePlayers.TabIndex = 0;
            groupBoxOnlinePlayers.TabStop = false;
            groupBoxOnlinePlayers.Text = "Online Players";
            textBoxSearchLogs.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            textBoxSearchLogs.Location = new Point(980, 5);
            textBoxSearchLogs.Name = "textBoxSearchLogs";
            textBoxSearchLogs.Size = new Size(114, 23);
            textBoxSearchLogs.TabIndex = 1;
            labelSearchLogs.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            labelSearchLogs.AutoSize = true;
            labelSearchLogs.Location = new Point(900, 8);
            labelSearchLogs.Name = "labelSearchLogs";
            labelSearchLogs.Size = new Size(74, 15);
            labelSearchLogs.TabIndex = 0;
            labelSearchLogs.Text = "Search logs:";
            tabPagePlayers.Controls.Add(listViewPlayers);
            tabPagePlayers.Location = new Point(4, 24);
            tabPagePlayers.Name = "tabPagePlayers";
            tabPagePlayers.Padding = new Padding(3);
            tabPagePlayers.Size = new Size(792, 372);
            tabPagePlayers.TabIndex = 1;
            tabPagePlayers.Text = "Players";
            tabPagePlayers.UseVisualStyleBackColor = true;
            listViewPlayers.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listViewPlayers.Columns.AddRange(new ColumnHeader[] { columnHeaderName, columnHeaderSteamID, columnHeaderIP, columnHeaderConnected });
            listViewPlayers.FullRowSelect = true;
            listViewPlayers.GridLines = true;
            listViewPlayers.Location = new Point(6, 6);
            listViewPlayers.Name = "listViewPlayers";
            listViewPlayers.Size = new Size(780, 360);
            listViewPlayers.TabIndex = 0;
            listViewPlayers.UseCompatibleStateImageBehavior = false;
            listViewPlayers.View = View.Details;
            columnHeaderName.Text = "Name";
            columnHeaderName.Width = 200;
            columnHeaderSteamID.Text = "Steam ID";
            columnHeaderSteamID.Width = 150;
            columnHeaderIP.Text = "IP Address";
            columnHeaderIP.Width = 150;
            columnHeaderConnected.Text = "Connected";
            columnHeaderConnected.Width = 150;
            panelRight.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right;
            panelRight.Controls.Add(groupBoxScheduledCommands);
            panelRight.Controls.Add(groupBoxTriggeredCommands);
            panelRight.Controls.Add(groupBoxHighlightSystem);
            panelRight.Controls.Add(groupBoxConsoleFilters);
            panelRight.Location = new Point(800, 24);
            panelRight.Name = "panelRight";
            panelRight.Size = new Size(400, 400);
            panelRight.TabIndex = 2;
            groupBoxScheduledCommands.Controls.Add(listBoxScheduledCommands);
            groupBoxScheduledCommands.Controls.Add(buttonNewScheduledCommand);
            groupBoxScheduledCommands.Location = new Point(3, 3);
            groupBoxScheduledCommands.Name = "groupBoxScheduledCommands";
            groupBoxScheduledCommands.Size = new Size(394, 90);
            groupBoxScheduledCommands.TabIndex = 0;
            groupBoxScheduledCommands.TabStop = false;
            groupBoxScheduledCommands.Text = "Scheduled commands";
            listBoxScheduledCommands.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listBoxScheduledCommands.FormattingEnabled = true;
            listBoxScheduledCommands.ItemHeight = 15;
            listBoxScheduledCommands.Location = new Point(6, 20);
            listBoxScheduledCommands.Name = "listBoxScheduledCommands";
            listBoxScheduledCommands.Size = new Size(300, 64);
            listBoxScheduledCommands.TabIndex = 1;
            buttonNewScheduledCommand.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonNewScheduledCommand.Location = new Point(312, 20);
            buttonNewScheduledCommand.Name = "buttonNewScheduledCommand";
            buttonNewScheduledCommand.Size = new Size(75, 23);
            buttonNewScheduledCommand.TabIndex = 0;
            buttonNewScheduledCommand.Text = "New command";
            buttonNewScheduledCommand.UseVisualStyleBackColor = true;
            groupBoxTriggeredCommands.Controls.Add(listBoxTriggeredCommands);
            groupBoxTriggeredCommands.Controls.Add(buttonNewTriggeredCommand);
            groupBoxTriggeredCommands.Location = new Point(3, 99);
            groupBoxTriggeredCommands.Name = "groupBoxTriggeredCommands";
            groupBoxTriggeredCommands.Size = new Size(394, 90);
            groupBoxTriggeredCommands.TabIndex = 1;
            groupBoxTriggeredCommands.TabStop = false;
            groupBoxTriggeredCommands.Text = "Triggered commands";
            listBoxTriggeredCommands.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listBoxTriggeredCommands.FormattingEnabled = true;
            listBoxTriggeredCommands.ItemHeight = 15;
            listBoxTriggeredCommands.Location = new Point(6, 20);
            listBoxTriggeredCommands.Name = "listBoxTriggeredCommands";
            listBoxTriggeredCommands.Size = new Size(300, 64);
            listBoxTriggeredCommands.TabIndex = 1;
            buttonNewTriggeredCommand.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonNewTriggeredCommand.Location = new Point(312, 20);
            buttonNewTriggeredCommand.Name = "buttonNewTriggeredCommand";
            buttonNewTriggeredCommand.Size = new Size(75, 23);
            buttonNewTriggeredCommand.TabIndex = 0;
            buttonNewTriggeredCommand.Text = "New command";
            buttonNewTriggeredCommand.UseVisualStyleBackColor = true;
            groupBoxHighlightSystem.Controls.Add(listBoxHighlights);
            groupBoxHighlightSystem.Controls.Add(buttonAddHighlight);
            groupBoxHighlightSystem.Location = new Point(3, 195);
            groupBoxHighlightSystem.Name = "groupBoxHighlightSystem";
            groupBoxHighlightSystem.Size = new Size(394, 90);
            groupBoxHighlightSystem.TabIndex = 2;
            groupBoxHighlightSystem.TabStop = false;
            groupBoxHighlightSystem.Text = "Highlight system";
            listBoxHighlights.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listBoxHighlights.FormattingEnabled = true;
            listBoxHighlights.ItemHeight = 15;
            listBoxHighlights.Location = new Point(6, 20);
            listBoxHighlights.Name = "listBoxHighlights";
            listBoxHighlights.Size = new Size(300, 64);
            listBoxHighlights.TabIndex = 1;
            buttonAddHighlight.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonAddHighlight.Location = new Point(312, 20);
            buttonAddHighlight.Name = "buttonAddHighlight";
            buttonAddHighlight.Size = new Size(75, 23);
            buttonAddHighlight.TabIndex = 0;
            buttonAddHighlight.Text = "Add";
            buttonAddHighlight.UseVisualStyleBackColor = true;
            groupBoxConsoleFilters.Controls.Add(listBoxFilters);
            groupBoxConsoleFilters.Controls.Add(buttonNewFilter);
            groupBoxConsoleFilters.Location = new Point(3, 291);
            groupBoxConsoleFilters.Name = "groupBoxConsoleFilters";
            groupBoxConsoleFilters.Size = new Size(394, 90);
            groupBoxConsoleFilters.TabIndex = 3;
            groupBoxConsoleFilters.TabStop = false;
            groupBoxConsoleFilters.Text = "Console filters";
            listBoxFilters.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            listBoxFilters.FormattingEnabled = true;
            listBoxFilters.ItemHeight = 15;
            listBoxFilters.Location = new Point(6, 20);
            listBoxFilters.Name = "listBoxFilters";
            listBoxFilters.Size = new Size(300, 64);
            listBoxFilters.TabIndex = 1;
            buttonNewFilter.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            buttonNewFilter.Location = new Point(312, 20);
            buttonNewFilter.Name = "buttonNewFilter";
            buttonNewFilter.Size = new Size(75, 23);
            buttonNewFilter.TabIndex = 0;
            buttonNewFilter.Text = "New filter";
            buttonNewFilter.UseVisualStyleBackColor = true;
            panelBottom.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            panelBottom.Location = new Point(0, 424);
            panelBottom.Name = "panelBottom";
            panelBottom.Size = new Size(1200, 30);
            panelBottom.TabIndex = 3;
            statusStrip.Items.AddRange(new ToolStripItem[] { toolStripStatusLabel, toolStripStatusLabelConnected, toolStripStatusLabelPlayers });
            statusStrip.Location = new Point(0, 454);
            statusStrip.Name = "statusStrip";
            statusStrip.Size = new Size(1200, 22);
            statusStrip.TabIndex = 4;
            statusStrip.Text = "statusStrip1";
            toolStripStatusLabel.Name = "toolStripStatusLabel";
            toolStripStatusLabel.Size = new Size(123, 17);
            toolStripStatusLabel.Text = "";
            toolStripStatusLabel.Click += toolStripStatusLabel_Click;
            toolStripStatusLabelConnected.Name = "toolStripStatusLabelConnected";
            toolStripStatusLabelConnected.Size = new Size(79, 17);
            toolStripStatusLabelConnected.Text = "Disconnected";
            toolStripStatusLabelPlayers.Name = "toolStripStatusLabelPlayers";
            toolStripStatusLabelPlayers.Size = new Size(67, 17);
            toolStripStatusLabelPlayers.Text = "Players: 0/0";
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackgroundImageLayout = ImageLayout.Stretch;
            ClientSize = new Size(1200, 476);
            Controls.Add(statusStrip);
            Controls.Add(panelBottom);
            Controls.Add(tabControl);
            Controls.Add(menuStrip);
            MainMenuStrip = menuStrip;
            Name = "Form1";
            Text = "RconRust";
            WindowState = FormWindowState.Maximized;
            FormClosing += Form1_FormClosing;
            menuStrip.ResumeLayout(false);
            menuStrip.PerformLayout();
            tabControl.ResumeLayout(false);
            tabPageConsole.ResumeLayout(false);
            panelConsoleControls.ResumeLayout(false);
            panelConsoleControls.PerformLayout();
            panelLeft.ResumeLayout(false);
            panelStatisticsMain.ResumeLayout(false);
            panelStatisticsMain.PerformLayout();
            panelStatsControls.ResumeLayout(false);
            panelStatsControls.PerformLayout();
            panelStatisticsRight.ResumeLayout(false);
            groupBoxOnlinePlayers.ResumeLayout(false);
            groupBoxOnlinePlayers.PerformLayout();
            tabPagePlayers.ResumeLayout(false);
            panelRight.ResumeLayout(false);
            groupBoxScheduledCommands.ResumeLayout(false);
            groupBoxTriggeredCommands.ResumeLayout(false);
            groupBoxHighlightSystem.ResumeLayout(false);
            groupBoxConsoleFilters.ResumeLayout(false);
            statusStrip.ResumeLayout(false);
            statusStrip.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip;
        private System.Windows.Forms.ToolStripMenuItem serverToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem connectToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem disconnectToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem styleToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabPageConsole;
        private System.Windows.Forms.RichTextBox richTextBoxLogs;
        private System.Windows.Forms.Panel panelConsoleControls;
        private System.Windows.Forms.TextBox textBoxSearchLogs;
        private System.Windows.Forms.Label labelSearchLogs;
        private System.Windows.Forms.TabPage tabPagePlayers;
        private System.Windows.Forms.ListView listViewPlayers;
        private System.Windows.Forms.ColumnHeader columnHeaderName;
        private System.Windows.Forms.ColumnHeader columnHeaderSteamID;
        private System.Windows.Forms.ColumnHeader columnHeaderIP;
        private System.Windows.Forms.ColumnHeader columnHeaderConnected;
        private System.Windows.Forms.ListView listViewBans;
        private System.Windows.Forms.ColumnHeader columnHeaderBanName;
        private System.Windows.Forms.ColumnHeader columnHeaderBanSteamID;
        private System.Windows.Forms.ColumnHeader columnHeaderBanReason;
        private System.Windows.Forms.ColumnHeader columnHeaderBanDate;
        private System.Windows.Forms.Panel panelStatisticsMain;
        private System.Windows.Forms.ListView listViewPlayerStats;
        private System.Windows.Forms.ColumnHeader columnHeaderStatsSteamID;
        private System.Windows.Forms.ColumnHeader columnHeaderNickname;
        private System.Windows.Forms.ColumnHeader columnHeaderPVPKills;
        private System.Windows.Forms.ColumnHeader columnHeaderPVPDeaths;
        private System.Windows.Forms.ColumnHeader columnHeaderPVEDeaths;
        private System.Windows.Forms.Panel panelStatsControls;
        private System.Windows.Forms.Label labelPlayerCount;
        private System.Windows.Forms.TextBox textBoxFilterStats;
        private System.Windows.Forms.Label labelFilterStats;
        private System.Windows.Forms.ListView listViewPlayerKills;
        private System.Windows.Forms.ColumnHeader columnHeaderKillDate;
        private System.Windows.Forms.ColumnHeader columnHeaderKillType;
        private System.Windows.Forms.ColumnHeader columnHeaderKillTarget;
        private System.Windows.Forms.Label labelPlayerKills;
        private System.Windows.Forms.Panel panelStatisticsRight;
        private System.Windows.Forms.GroupBox groupBoxOnlinePlayers;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanelPlayers;
        private System.Windows.Forms.Label labelOnlineCount;
        private System.Windows.Forms.Panel panelRight;
        private System.Windows.Forms.GroupBox groupBoxScheduledCommands;
        private System.Windows.Forms.ListBox listBoxScheduledCommands;
        private System.Windows.Forms.Button buttonNewScheduledCommand;
        private System.Windows.Forms.GroupBox groupBoxTriggeredCommands;
        private System.Windows.Forms.ListBox listBoxTriggeredCommands;
        private System.Windows.Forms.Button buttonNewTriggeredCommand;
        private System.Windows.Forms.GroupBox groupBoxHighlightSystem;
        private System.Windows.Forms.ListBox listBoxHighlights;
        private System.Windows.Forms.Button buttonAddHighlight;
        private System.Windows.Forms.GroupBox groupBoxConsoleFilters;
        private System.Windows.Forms.ListBox listBoxFilters;
        private System.Windows.Forms.Button buttonNewFilter;
        private System.Windows.Forms.Panel panelBottom;
        private System.Windows.Forms.TextBox textBoxChatMessage;
        private System.Windows.Forms.TextBox textBoxCommand;
        private System.Windows.Forms.Button buttonSendCommand;
        private System.Windows.Forms.StatusStrip statusStrip;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabelConnected;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabelPlayers;
        private System.Windows.Forms.Panel panelLeft;
        private System.Windows.Forms.GroupBox groupBoxPlayers;
        private System.Windows.Forms.TextBox textBoxPlayerSearch;
    }
}